### ISSUE TITLE
Missing version number

### ISSUE THREAD

**Issue by stefanofinetti** [Fragtality/Fenix2GSX#41] opened 2023-09-07 07:57 UTC
Hi, I know this is not technically an Issue, just a slight improvement to make it easier to track updates of this beautiful little software (I can't fly my Fenix without it anymore!).
Could you please add somewhere in the window the current software version? In this case it would be easier to know when to update it. I don't remember if I have already downloaded the latest RC candidate and can't verify unless I go inside the app with right click and check the version. Doable, but not very user friendly :-)

**Comment by Fragtality** [comment] 2023-09-07 17:38
Duplicate of #38

**Closed by Fragtality** 2023-09-07 17:38 UTC
